name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git binfmt-support xz-utils

      - name: Download Raspberry Pi OS image
        run: |
          wget -q "http://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2024-11-19/2024-11-19-raspios-bookworm-arm64-lite.img.xz"
          unxz *.img.xz

      - name: Create Raspberry Pi OS sysroot
        run: |
          export SYSROOT=/opt/rpi-sysroot
          sudo kpartx -a -v *.img
          sudo mount -o loop /dev/mapper/loop3p2 /mnt # Why loop3 here?
          sudo cp -r /mnt $SYSROOT # Why not put unionfs on it and use it directly without copying?
          sudo mount --bind /dev $SYSROOT/dev
          sudo mount --bind /proc $SYSROOT/proc
          sudo mount --bind /sys $SYSROOT/sys
          sudo mount -t tmpfs tmpfs $SYSROOT/tmp
          # sudo cp /etc/resolv.conf $SYSROOT/etc/resolv.conf
          echo "nameserver 1.1.1.1" | sudo tee $SYSROOT/etc/resolv.conf
          sudo sed -i 's/^/#/' $SYSROOT/etc/ld.so.preload || true # Needed?
          echo 'Acquire::Check-Valid-Until "false";' | sudo tee $SYSROOT//etc/apt/apt.conf.d/99disable-release-check

      - name: Chroot into Raspberry Pi OS sysroot
        run: |
          export SYSROOT=/opt/rpi-sysroot
          sudo cp *.sh $SYSROOT
          sudo chroot $SYSROOT bash -ex /macemu.sh
          sudo chroot $SYSROOT bash -ex /qemu.sh

      - name: Unmount Raspberry Pi OS sysroot
        run: |
          sudo umount $SYSROOT/tmp
          sudo umount $SYSROOT/dev
          sudo umount $SYSROOT/proc
          sudo umount $SYSROOT/sys
          sudo umount /mnt
